# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "JussiKalliola"
repo_name: "offlading-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True

# file paths
json_readme_path: './docs/offloading-arxiv-daily.json'
json_gitpage_path: './docs/offloading-arxiv-daily-web.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'

# keywords to search
keywords:
    "Offloading": 
        filters: ["Task Offloading", "Computation Offloading"]
